/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ReadRootGet$Params as ReadRootGet$Params } from './fn/operations/read-root-get';
export { readRootGet as readRootGet } from './fn/operations/read-root-get';
export type { GetPeople$Params as GetPeople$Params } from './fn/operations/get-people';
export { getPeople as getPeople } from './fn/operations/get-people';
export type { AddPerson$Params as AddPerson$Params } from './fn/operations/add-person';
export { addPerson as addPerson } from './fn/operations/add-person';
