/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { HttpValidationError } from './models/http-validation-error';
export type { Person } from './models/person';
export type { PersonCreate } from './models/person-create';
export type { ValidationError } from './models/validation-error';
