/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Person } from '../../models/person';
import { PersonCreate } from '../../models/person-create';

export interface AddPerson$Params {
      body: PersonCreate
}

export function addPerson(http: HttpClient, rootUrl: string, params: AddPerson$Params, context?: HttpContext): Observable<StrictHttpResponse<Person>> {
  const rb = new RequestBuilder(rootUrl, addPerson.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Person>;
    })
  );
}

addPerson.PATH = '/addPerson';
